---

# Package installation management

- name: 'INSTALL | Ensure Zeppelin root folder exists'
  file:
    path: "{{ zeppelin_root_folder.path }}"
    owner: "{{ zeppelin_root_folder.user }}"
    group: "{{ zeppelin_root_folder.group }}"
    mode: "{{ zeppelin_root_folder.mode }}"
    state: 'directory'


- name: 'INSTALL | Check if needed version is already installed'
  stat:
    path: "{{ zeppelin_root_folder.path }}/{{ zeppelin_package }}"
  register: 'check_zeppelin_install_path'


- name: 'INSTALL | Download Zeppelin package if needed'
  get_url:
    url: "{{ zeppelin_download_url }}"
    dest: '/tmp/'
  when: "check_zeppelin_install_path.stat.exists == False"


- name: 'INSTALL | Extract Zeppelin into the root directory'
  unarchive:
    src: "/tmp/{{ zeppelin_package_filename }}"
    dest: "{{ zeppelin_root_folder.path }}/"
    copy: no
    owner: "{{ zeppelin_user.name }}"
    group: "{{ zeppelin_group.name }}"
  when: "check_zeppelin_install_path.stat.exists == False"


- name: 'INSTALL | Ensure current symlink targets the needed version'
  file:
    src: "{{ zeppelin_root_folder.path }}/{{ zeppelin_package }}"
    dest: "{{ zeppelin_root_folder.path }}/current"
    owner: "{{ zeppelin_user.name }}"
    group: "{{ zeppelin_group.name }}"
    state: 'link'
